// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVTmNmwtgMf3Le_qnpGevjqVE1b0kqFLQ',
    appId: '1:135035254789:web:b746d4b1b0660677e5446c',
    messagingSenderId: '135035254789',
    projectId: 'proyecto-interciclo-cp',
    authDomain: 'proyecto-interciclo-cp.firebaseapp.com',
    storageBucket: 'proyecto-interciclo-cp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD33mRNHpslvJhjOmmKwB9d73vAXRrxtcM',
    appId: '1:135035254789:android:3a4ee26d92a6b93ee5446c',
    messagingSenderId: '135035254789',
    projectId: 'proyecto-interciclo-cp',
    storageBucket: 'proyecto-interciclo-cp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa6Gb27ZIowW9GL8h90cCSrXVwZ5IDxCI',
    appId: '1:135035254789:ios:d2236e7adede4a30e5446c',
    messagingSenderId: '135035254789',
    projectId: 'proyecto-interciclo-cp',
    storageBucket: 'proyecto-interciclo-cp.firebasestorage.app',
    iosBundleId: 'com.example.upsglam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa6Gb27ZIowW9GL8h90cCSrXVwZ5IDxCI',
    appId: '1:135035254789:ios:d2236e7adede4a30e5446c',
    messagingSenderId: '135035254789',
    projectId: 'proyecto-interciclo-cp',
    storageBucket: 'proyecto-interciclo-cp.firebasestorage.app',
    iosBundleId: 'com.example.upsglam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVTmNmwtgMf3Le_qnpGevjqVE1b0kqFLQ',
    appId: '1:135035254789:web:b5c3dbb929126305e5446c',
    messagingSenderId: '135035254789',
    projectId: 'proyecto-interciclo-cp',
    authDomain: 'proyecto-interciclo-cp.firebaseapp.com',
    storageBucket: 'proyecto-interciclo-cp.firebasestorage.app',
  );
}
